In [281]:
import numpy as np
import pandas as pd
#import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.max_colwidth', None)
import warnings
warnings.filterwarnings('ignore')
from datetime import datetime, timedelta
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

2025-01-26 15:50:21.009346: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
df_ev = pd.read_csv("data/cleaned_chargingdata.csv")
df_weather = pd.read_csv("data/cleaned_weather_data.csv")

In [3]:
df_ev

,Unnamed: 0.1,Unnamed: 0,id,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,chargingDuration
0,0,0,5e23b149f9af8b5fe4b973cf,2020-01-02 05:08:54-08:00,2020-01-02 11:11:15-08:00,2020-01-02 09:31:35-08:00,25.016,1_1_179_810_2020-01-02 13:08:53.870034,1,AG-3F30,1-1-179-810,America/Los_Angeles,194.0,262.683333
1,1,1,5e23b149f9af8b5fe4b973d0,2020-01-02 05:36:50-08:00,2020-01-02 14:38:21-08:00,2020-01-02 12:18:05-08:00,33.097,1_1_193_825_2020-01-02 13:36:49.599853,1,AG-1F01,1-1-193-825,America/Los_Angeles,4275.0,401.250000
2,2,2,5e23b149f9af8b5fe4b973d1,2020-01-02 05:56:35-08:00,2020-01-02 16:39:22-08:00,2020-01-02 08:35:06-08:00,6.521,1_1_193_829_2020-01-02 13:56:35.214993,1,AG-1F03,1-1-193-829,America/Los_Angeles,344.0,158.516667
3,3,3,5e23b149f9af8b5fe4b973d2,2020-01-02 05:59:58-08:00,2020-01-02 08:38:39-08:00,2020-01-02 07:18:45-08:00,2.355,1_1_193_820_2020-01-02 13:59:58.309319,1,AG-1F04,1-1-193-820,America/Los_Angeles,1117.0,78.783333
4,4,4,5e23b149f9af8b5fe4b973d3,2020-01-02 06:00:01-08:00,2020-01-02 14:08:40-08:00,2020-01-02 10:17:30-08:00,13.375,1_1_193_819_2020-01-02 14:00:00.779967,1,AG-1F06,1-1-193-819,America/Los_Angeles,334.0,257.483333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64987,65032,8670,5d2fbdd3f9af8b4d0dd0d54a,2019-07-01 14:49:12-07:00,2019-07-01 18:37:18-07:00,2019-07-01 16:14:33-07:00,8.399,1_1_179_798_2019-07-01 21:49:11.873404,1,AG-3F18,1-1-179-798,America/Los_Angeles,1346.0,85.350000
64988,65033,8671,5d2fbdd3f9af8b4d0dd0d54b,2019-07-01 14:58:45-07:00,2019-07-01 17:39:48-07:00,2019-07-01 17:39:48-07:00,16.864,1_1_179_794_2019-07-01 21:58:44.571011,1,AG-3F20,1-1-179-794,America/Los_Angeles,364.0,161.050000
64989,65034,8672,5d2fbdd3f9af8b4d0dd0d54c,2019-07-01 15:02:21-07:00,2019-07-01 17:58:50-07:00,2019-07-01 17:58:50-07:00,18.335,1_1_191_807_2019-07-01 22:02:20.810735,1,AG-4F47,1-1-191-807,America/Los_Angeles,2050.0,176.483333
64990,65035,8673,5d2fbdd3f9af8b4d0dd0d54d,2019-07-01 15:23:44-07:00,2019-07-01 19:03:36-07:00,2019-07-01 19:03:36-07:00,22.815,1_1_179_781_2019-07-01 22:23:32.496137,1,AG-3F31,1-1-179-781,America/Los_Angeles,1626.0,219.866667
64991,65036,8674,5d2fbdd3f9af8b4d0dd0d54e,2019-07-01 15:36:08-07:00,2019-07-01 18:10:52-07:00,2019-07-01 17:24:32-07:00,10.241,1_1_193_819_2019-07-01 22:35:56.104381,1,AG-1F06,1-1-193-819,America/Los_Angeles,2299.0,108.400000

In [4]:
df_ev[df_ev.id == '5ea3848df9af8b428bf97225']

,Unnamed: 0.1,Unnamed: 0,id,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,chargingDuration
3756,3756,3756,5ea3848df9af8b428bf97225,2020-04-08 09:36:53-07:00,2020-04-08 20:43:29-07:00,2020-04-08 20:43:29-07:00,25.183,1_1_194_822_2020-04-08 16:36:53.316264,1,AG-1F12,1-1-194-822,America/Los_Angeles,507.0,666.6

In [5]:
test = df_ev[df_ev.doneChargingTime.isna()]
test

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, id, connectionTime, disconnectTime, doneChargingTime, kWhDelivered, sessionID, siteID, spaceID, stationID, timezone, userID, chargingDuration]
Index: []

In [6]:
df_ev['sessionID'].value_counts()

sessionID
1_1_179_810_2020-01-02 13:08:53.870034    1
2_39_127_19_2018-10-25 15:29:41.347098    1
2_39_79_376_2018-10-25 14:20:43.833640    1
2_39_138_29_2018-10-25 14:32:34.910076    1
2_39_79_377_2018-10-25 14:46:02.608536    1
                                         ..
2_39_127_19_2019-02-16 21:07:35.064898    1
2_39_79_379_2019-02-16 21:17:26.749878    1
2_39_83_386_2019-02-16 22:28:31.358531    1
2_39_125_21_2019-02-16 23:28:58.650931    1
1_1_193_819_2019-07-01 22:35:56.104381    1
Name: count, Length: 64992, dtype: int64

In [7]:
df_ev_ur = df_ev.drop_duplicates(subset='id', keep='first')

In [8]:
df_ev_ur.dtypes

Unnamed: 0.1          int64
Unnamed: 0            int64
id                   object
connectionTime       object
disconnectTime       object
doneChargingTime     object
kWhDelivered        float64
sessionID            object
siteID                int64
spaceID              object
stationID            object
timezone             object
userID              float64
chargingDuration    float64
dtype: object

In [9]:
# Remove timezone offset information from the string column before conversion
df_ev_ur['connectionTime'] = df_ev_ur['connectionTime'].str.replace(r'(-08:00)|(-07:00)', '', regex=True)
df_ev_ur['disconnectTime'] = df_ev_ur['disconnectTime'].str.replace(r'(-08:00)|(-07:00)', '', regex=True)
df_ev_ur['doneChargingTime'] = df_ev_ur['doneChargingTime'].str.replace(r'(-08:00)|(-07:00)', '', regex=True)

In [10]:
# Ensure the columns are converted to datetime 
df_ev_ur['connectionTime'] = pd.to_datetime(df_ev_ur['connectionTime'], errors='coerce')
df_ev_ur['disconnectTime'] = pd.to_datetime(df_ev_ur['disconnectTime'], errors='coerce')
df_ev_ur['doneChargingTime'] = pd.to_datetime(df_ev_ur['doneChargingTime'], errors='coerce')

In [11]:
df_ev_ur.dtypes

Unnamed: 0.1                 int64
Unnamed: 0                   int64
id                          object
connectionTime      datetime64[ns]
disconnectTime      datetime64[ns]
doneChargingTime    datetime64[ns]
kWhDelivered               float64
sessionID                   object
siteID                       int64
spaceID                     object
stationID                   object
timezone                    object
userID                     float64
chargingDuration           float64
dtype: object

In [12]:
df_ev_ur

,Unnamed: 0.1,Unnamed: 0,id,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,chargingDuration
0,0,0,5e23b149f9af8b5fe4b973cf,2020-01-02 05:08:54,2020-01-02 11:11:15,2020-01-02 09:31:35,25.016,1_1_179_810_2020-01-02 13:08:53.870034,1,AG-3F30,1-1-179-810,America/Los_Angeles,194.0,262.683333
1,1,1,5e23b149f9af8b5fe4b973d0,2020-01-02 05:36:50,2020-01-02 14:38:21,2020-01-02 12:18:05,33.097,1_1_193_825_2020-01-02 13:36:49.599853,1,AG-1F01,1-1-193-825,America/Los_Angeles,4275.0,401.250000
2,2,2,5e23b149f9af8b5fe4b973d1,2020-01-02 05:56:35,2020-01-02 16:39:22,2020-01-02 08:35:06,6.521,1_1_193_829_2020-01-02 13:56:35.214993,1,AG-1F03,1-1-193-829,America/Los_Angeles,344.0,158.516667
3,3,3,5e23b149f9af8b5fe4b973d2,2020-01-02 05:59:58,2020-01-02 08:38:39,2020-01-02 07:18:45,2.355,1_1_193_820_2020-01-02 13:59:58.309319,1,AG-1F04,1-1-193-820,America/Los_Angeles,1117.0,78.783333
4,4,4,5e23b149f9af8b5fe4b973d3,2020-01-02 06:00:01,2020-01-02 14:08:40,2020-01-02 10:17:30,13.375,1_1_193_819_2020-01-02 14:00:00.779967,1,AG-1F06,1-1-193-819,America/Los_Angeles,334.0,257.483333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64987,65032,8670,5d2fbdd3f9af8b4d0dd0d54a,2019-07-01 14:49:12,2019-07-01 18:37:18,2019-07-01 16:14:33,8.399,1_1_179_798_2019-07-01 21:49:11.873404,1,AG-3F18,1-1-179-798,America/Los_Angeles,1346.0,85.350000
64988,65033,8671,5d2fbdd3f9af8b4d0dd0d54b,2019-07-01 14:58:45,2019-07-01 17:39:48,2019-07-01 17:39:48,16.864,1_1_179_794_2019-07-01 21:58:44.571011,1,AG-3F20,1-1-179-794,America/Los_Angeles,364.0,161.050000
64989,65034,8672,5d2fbdd3f9af8b4d0dd0d54c,2019-07-01 15:02:21,2019-07-01 17:58:50,2019-07-01 17:58:50,18.335,1_1_191_807_2019-07-01 22:02:20.810735,1,AG-4F47,1-1-191-807,America/Los_Angeles,2050.0,176.483333
64990,65035,8673,5d2fbdd3f9af8b4d0dd0d54d,2019-07-01 15:23:44,2019-07-01 19:03:36,2019-07-01 19:03:36,22.815,1_1_179_781_2019-07-01 22:23:32.496137,1,AG-3F31,1-1-179-781,America/Los_Angeles,1626.0,219.866667
64991,65036,8674,5d2fbdd3f9af8b4d0dd0d54e,2019-07-01 15:36:08,2019-07-01 18:10:52,2019-07-01 17:24:32,10.241,1_1_193_819_2019-07-01 22:35:56.104381,1,AG-1F06,1-1-193-819,America/Los_Angeles,2299.0,108.400000

In [13]:
df_ev_ur.spaceID.value_counts()

spaceID
CA-303     1804
AG-1F08    1448
CA-305     1411
AG-1F10    1265
AG-1F06    1203
           ...
CA-509       88
CA-149       76
CA-505       75
CA-213       15
CA-148        8
Name: count, Length: 107, dtype: int64

In [14]:
site1 = df_ev_ur[df_ev_ur.siteID == 1]
site1.spaceID.unique()

array(['AG-3F30', 'AG-1F01', 'AG-1F03', 'AG-1F04', 'AG-1F06', 'AG-1F13',
       'AG-1F09', 'AG-4F34', 'AG-1F11', 'AG-1F08', 'AG-3F22', 'AG-1F14',
       'AG-1F07', 'AG-1F12', 'AG-3F29', 'AG-1F05', 'AG-3F18', 'AG-1F10',
       'AG-3F16', 'AG-4F37', 'AG-1F02', 'AG-3F28', 'AG-3F25', 'AG-3F24',
       'AG-3F33', 'AG-3F23', 'AG-3F31', 'AG-3F32', 'AG-3F27', 'AG-3F26',
       'AG-3F20', 'AG-3F17', 'AG-3F21', 'AG-3F19', 'AG-4F44', 'AG-4F52',
       'AG-4F41', 'AG-4F48', 'AG-4F35', 'AG-4F50', 'AG-3F15', 'AG-4F51',
       'AG-4F47', 'AG-4F46', 'AG-4F49', 'AG-4F43', 'AG-4F42', 'AG-4F45',
       'AG-4F36', 'AG-4F38', 'AG-4F40', 'AG-4F39'], dtype=object)

In [15]:
site2 = df_ev_ur[df_ev_ur.siteID == 2]
site2.spaceID.unique()

array(['CA-512', 'CA-327', 'CA-326', 'CA-303', 'CA-325', 'CA-311',
       'CA-309', 'CA-491', 'CA-493', 'CA-499', 'CA-323', 'CA-313',
       'CA-324', 'CA-513', 'CA-305', 'CA-317', 'CA-510', 'CA-315',
       'CA-321', 'CA-490', 'CA-497', 'CA-489', 'CA-319', 'CA-492',
       'CA-494', 'CA-502', 'CA-500', 'CA-495', 'CA-498', 'CA-304',
       'CA-307', 'CA-306', 'CA-501', 'CA-318', 'CA-308', 'CA-316',
       'CA-312', 'CA-320', 'CA-212', 'CA-508', 'CA-322', 'CA-314',
       'CA-503', 'CA-504', 'CA-496', 'CA-310', 'CA-506', 'CA-149',
       'CA-509', 'CA-507', 'CA-511', 'CA-213', 'CA-505', 'CA-148',
       '11900388'], dtype=object)

## logic to compute hourly maximum observed utilization rate per site

In [16]:
# Define the total number of spaces per site (example values)
total_spaces = {
    1: 52,  # Replace with the actual number of spaces for site 1
    2: 54   # Replace with the actual number of spaces for site 2
}

# Create a new DataFrame to hold hourly data
start_time = df_ev_ur['connectionTime'].min().replace(minute=0, second=0, microsecond=0)
end_time = df_ev_ur['disconnectTime'].max().replace(minute=0, second=0, microsecond=0) + timedelta(hours=1)

# Generate hourly intervals
times = pd.date_range(start=start_time, end=end_time, freq='H')
hourly_data = []

for time in times:
    # For each hour, calculate utilization for each site
    hourly_entry = {'hour': time}
    for site in total_spaces.keys():
        # Filter sessions active during the hour for the site
        active_sessions = df_ev_ur[(df_ev_ur['siteID'] == site) &
                             (df_ev_ur['connectionTime'] <= time + timedelta(hours=1)) &
                             (df_ev_ur['disconnectTime'] > time)]

        # Calculate utilization rate
        utilization = len(active_sessions['spaceID'].unique()) / total_spaces[site]
        hourly_entry[f'utilization_{site}'] = utilization

    hourly_data.append(hourly_entry)

# Create DataFrame for hourly utilization
hourly_df = pd.DataFrame(hourly_data)

# Display the result
hourly_df.head()

                 hour  utilization_1  utilization_2
0 2018-04-25 04:00:00            0.0       0.018519
1 2018-04-25 05:00:00            0.0       0.018519
2 2018-04-25 06:00:00            0.0       0.055556
3 2018-04-25 07:00:00            0.0       0.129630
4 2018-04-25 08:00:00            0.0       0.407407

In [333]:
hourly_df

                     hour  utilization_1  utilization_2
0     2018-04-25 04:00:00            0.0       0.018519
1     2018-04-25 05:00:00            0.0       0.018519
2     2018-04-25 06:00:00            0.0       0.055556
3     2018-04-25 07:00:00            0.0       0.129630
4     2018-04-25 08:00:00            0.0       0.407407
...                   ...            ...            ...
23559 2020-12-31 19:00:00            0.0       0.000000
23560 2020-12-31 20:00:00            0.0       0.000000
23561 2020-12-31 21:00:00            0.0       0.000000
23562 2020-12-31 22:00:00            0.0       0.000000
23563 2020-12-31 23:00:00            0.0       0.000000

[23564 rows x 3 columns]