In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.max_colwidth', None)
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [2]:
df_ev = pd.read_csv("data/cleaned_chargingdata.csv")

In [3]:
df_ev

,Unnamed: 0.1,Unnamed: 0,id,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,WhPerMile,kWhRequested,milesRequested,minutesAvailable,modifiedAt,paymentRequired,requestedDeparture
0,0,0,5e23b149f9af8b5fe4b973cf,2020-01-02 05:08:54-08:00,2020-01-02 11:11:15-08:00,2020-01-02 09:31:35-08:00,25.016,1_1_179_810_2020-01-02 13:08:53.870034,1,AG-3F30,1-1-179-810,America/Los_Angeles,194.0,250.0,25.00,100.0,463.0,2020-01-02 05:09:39-08:00,True,2020-01-02 12:51:54-08:00
1,1,1,5e23b149f9af8b5fe4b973d0,2020-01-02 05:36:50-08:00,2020-01-02 14:38:21-08:00,2020-01-02 12:18:05-08:00,33.097,1_1_193_825_2020-01-02 13:36:49.599853,1,AG-1F01,1-1-193-825,America/Los_Angeles,4275.0,280.0,70.00,250.0,595.0,2020-01-02 05:37:11-08:00,True,2020-01-02 15:31:50-08:00
2,2,2,5e23b149f9af8b5fe4b973d1,2020-01-02 05:56:35-08:00,2020-01-02 16:39:22-08:00,2020-01-02 08:35:06-08:00,6.521,1_1_193_829_2020-01-02 13:56:35.214993,1,AG-1F03,1-1-193-829,America/Los_Angeles,344.0,400.0,8.00,20.0,60.0,2020-01-02 05:57:17-08:00,True,2020-01-02 06:56:35-08:00
3,3,3,5e23b149f9af8b5fe4b973d2,2020-01-02 05:59:58-08:00,2020-01-02 08:38:39-08:00,2020-01-02 07:18:45-08:00,2.355,1_1_193_820_2020-01-02 13:59:58.309319,1,AG-1F04,1-1-193-820,America/Los_Angeles,1117.0,400.0,8.00,20.0,65.0,2020-01-02 06:00:03-08:00,True,2020-01-02 07:04:58-08:00
4,4,3,5e23b149f9af8b5fe4b973d2,2020-01-02 05:59:58-08:00,2020-01-02 08:38:39-08:00,2020-01-02 07:18:45-08:00,2.355,1_1_193_820_2020-01-02 13:59:58.309319,1,AG-1F04,1-1-193-820,America/Los_Angeles,1117.0,400.0,8.00,20.0,65.0,2020-01-02 06:00:19-08:00,True,2020-01-02 07:04:58-08:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75324,80634,10083,5d574ad2f9af8b4c10c03652,2019-07-31 11:08:04-07:00,2019-07-31 16:29:18-07:00,2019-07-31 16:30:18-07:00,28.787,1_1_179_809_2019-07-31 18:08:04.432654,1,AG-3F27,1-1-179-809,America/Los_Angeles,393.0,240.0,31.20,130.0,355.0,2019-07-31 11:08:23-07:00,True,2019-07-31 17:03:04-07:00
75325,80635,10084,5d574ad2f9af8b4c10c03653,2019-07-31 11:40:41-07:00,2019-07-31 17:59:42-07:00,2019-07-31 14:44:23-07:00,7.787,1_1_179_810_2019-07-31 18:40:40.900203,1,AG-3F30,1-1-179-810,America/Los_Angeles,220.0,333.0,6.66,20.0,455.0,2019-07-31 11:41:02-07:00,True,2019-07-31 19:15:41-07:00
75326,80636,10085,5d574ad2f9af8b4c10c03654,2019-07-31 12:04:40-07:00,2019-07-31 15:44:22-07:00,2019-07-31 15:45:21-07:00,11.274,1_1_191_795_2019-07-31 19:04:40.098273,1,AG-4F51,1-1-191-795,America/Los_Angeles,1974.0,333.0,19.98,60.0,184.0,2019-07-31 12:04:57-07:00,True,2019-07-31 15:08:40-07:00
75327,80637,10086,5d574ad2f9af8b4c10c03655,2019-07-31 12:19:47-07:00,2019-07-31 17:34:51-07:00,2019-07-31 14:25:30-07:00,11.589,1_1_191_778_2019-07-31 19:19:46.919358,1,AG-4F43,1-1-191-778,America/Los_Angeles,942.0,275.0,22.00,80.0,60.0,2019-07-31 12:20:10-07:00,True,2019-07-31 13:19:47-07:00
75328,80638,10087,5d574ad2f9af8b4c10c03656,2019-07-31 12:21:47-07:00,2019-07-31 15:00:04-07:00,2019-07-31 13:51:34-07:00,0.897,1_1_178_817_2019-07-31 19:21:46.727697,1,AG-1F09,1-1-178-817,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN

In [4]:
df_ev['sessionID'].value_counts()

sessionID
1_1_179_779_2019-08-13 20:45:06.293662     58
1_1_178_824_2019-08-12 21:55:17.692457     46
1_1_194_822_2019-02-26 22:44:53.174959     32
2_39_79_379_2018-11-01 23:53:52.376186     27
2_39_131_30_2019-10-11 06:38:13.020209     25
                                           ..
2_39_124_558_2019-04-30 15:45:30.152741     1
2_39_123_23_2019-04-30 15:50:13.833702      1
2_39_92_442_2019-04-30 15:51:58.864062      1
2_39_79_377_2019-04-30 15:55:30.067900      1
1_1_193_819_2019-07-01 22:35:56.104381      1
Name: count, Length: 60950, dtype: int64

### There are multiple entries per sessionID for some, it's because they have multiple entries in the userInput column (with different modifiedAt times)
### For the cluster analysis, only one entry per sessionID/id will be used

In [5]:
df_ev_ca = df_ev.drop_duplicates(subset='id', keep='first')

In [6]:
df_ev_ca

,Unnamed: 0.1,Unnamed: 0,id,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,WhPerMile,kWhRequested,milesRequested,minutesAvailable,modifiedAt,paymentRequired,requestedDeparture
0,0,0,5e23b149f9af8b5fe4b973cf,2020-01-02 05:08:54-08:00,2020-01-02 11:11:15-08:00,2020-01-02 09:31:35-08:00,25.016,1_1_179_810_2020-01-02 13:08:53.870034,1,AG-3F30,1-1-179-810,America/Los_Angeles,194.0,250.0,25.00,100.0,463.0,2020-01-02 05:09:39-08:00,True,2020-01-02 12:51:54-08:00
1,1,1,5e23b149f9af8b5fe4b973d0,2020-01-02 05:36:50-08:00,2020-01-02 14:38:21-08:00,2020-01-02 12:18:05-08:00,33.097,1_1_193_825_2020-01-02 13:36:49.599853,1,AG-1F01,1-1-193-825,America/Los_Angeles,4275.0,280.0,70.00,250.0,595.0,2020-01-02 05:37:11-08:00,True,2020-01-02 15:31:50-08:00
2,2,2,5e23b149f9af8b5fe4b973d1,2020-01-02 05:56:35-08:00,2020-01-02 16:39:22-08:00,2020-01-02 08:35:06-08:00,6.521,1_1_193_829_2020-01-02 13:56:35.214993,1,AG-1F03,1-1-193-829,America/Los_Angeles,344.0,400.0,8.00,20.0,60.0,2020-01-02 05:57:17-08:00,True,2020-01-02 06:56:35-08:00
3,3,3,5e23b149f9af8b5fe4b973d2,2020-01-02 05:59:58-08:00,2020-01-02 08:38:39-08:00,2020-01-02 07:18:45-08:00,2.355,1_1_193_820_2020-01-02 13:59:58.309319,1,AG-1F04,1-1-193-820,America/Los_Angeles,1117.0,400.0,8.00,20.0,65.0,2020-01-02 06:00:03-08:00,True,2020-01-02 07:04:58-08:00
5,5,4,5e23b149f9af8b5fe4b973d3,2020-01-02 06:00:01-08:00,2020-01-02 14:08:40-08:00,2020-01-02 10:17:30-08:00,13.375,1_1_193_819_2020-01-02 14:00:00.779967,1,AG-1F06,1-1-193-819,America/Los_Angeles,334.0,400.0,16.00,40.0,504.0,2020-01-02 06:00:13-08:00,True,2020-01-02 14:24:01-08:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73563,78871,8670,5d2fbdd3f9af8b4d0dd0d54a,2019-07-01 14:49:12-07:00,2019-07-01 18:37:18-07:00,2019-07-01 16:14:33-07:00,8.399,1_1_179_798_2019-07-01 21:49:11.873404,1,AG-3F18,1-1-179-798,America/Los_Angeles,1346.0,400.0,32.00,80.0,36.0,2019-07-01 14:49:37-07:00,True,2019-07-01 15:25:12-07:00
73565,78873,8671,5d2fbdd3f9af8b4d0dd0d54b,2019-07-01 14:58:45-07:00,2019-07-01 17:39:48-07:00,2019-07-01 17:40:21-07:00,16.864,1_1_179_794_2019-07-01 21:58:44.571011,1,AG-3F20,1-1-179-794,America/Los_Angeles,364.0,400.0,40.00,100.0,234.0,2019-07-01 14:59:09-07:00,True,2019-07-01 18:52:45-07:00
73566,78874,8672,5d2fbdd3f9af8b4d0dd0d54c,2019-07-01 15:02:21-07:00,2019-07-01 17:58:50-07:00,2019-07-01 17:59:23-07:00,18.335,1_1_191_807_2019-07-01 22:02:20.810735,1,AG-4F47,1-1-191-807,America/Los_Angeles,2050.0,333.0,29.97,90.0,309.0,2019-07-01 15:02:37-07:00,True,2019-07-01 20:11:21-07:00
73568,78876,8673,5d2fbdd3f9af8b4d0dd0d54d,2019-07-01 15:23:44-07:00,2019-07-01 19:03:36-07:00,2019-07-01 19:04:06-07:00,22.815,1_1_179_781_2019-07-01 22:23:32.496137,1,AG-3F31,1-1-179-781,America/Los_Angeles,1626.0,200.0,34.00,170.0,99.0,2019-07-01 15:23:43-07:00,True,2019-07-01 17:02:44-07:00
73569,78877,8674,5d2fbdd3f9af8b4d0dd0d54e,2019-07-01 15:36:08-07:00,2019-07-01 18:10:52-07:00,2019-07-01 17:24:32-07:00,10.241,1_1_193_819_2019-07-01 22:35:56.104381,1,AG-1F06,1-1-193-819,America/Los_Angeles,2299.0,333.0,16.65,50.0,191.0,2019-07-01 15:36:08-07:00,True,2019-07-01 18:47:08-07:00

In [7]:
df_ev_ca.dtypes

Unnamed: 0.1            int64
Unnamed: 0              int64
id                     object
connectionTime         object
disconnectTime         object
doneChargingTime       object
kWhDelivered          float64
sessionID              object
siteID                  int64
spaceID                object
stationID              object
timezone               object
userID                float64
WhPerMile             float64
kWhRequested          float64
milesRequested        float64
minutesAvailable      float64
modifiedAt             object
paymentRequired          bool
requestedDeparture     object
dtype: object

### Fix dtypes for time columns

In [8]:
# Remove timezone offset information from the string column before conversion
df_ev_ca['connectionTime'] = df_ev_ca['connectionTime'].str.replace(r'(-08:00)|(-07:00)', '', regex=True)
df_ev_ca['disconnectTime'] = df_ev_ca['disconnectTime'].str.replace(r'(-08:00)|(-07:00)', '', regex=True)
df_ev_ca['doneChargingTime'] = df_ev_ca['doneChargingTime'].str.replace(r'(-08:00)|(-07:00)', '', regex=True)

In [9]:
# Ensure the columns are converted to datetime 
df_ev_ca['connectionTime'] = pd.to_datetime(df_ev_ca['connectionTime'], errors='coerce')
df_ev_ca['disconnectTime'] = pd.to_datetime(df_ev_ca['disconnectTime'], errors='coerce')
df_ev_ca['doneChargingTime'] = pd.to_datetime(df_ev_ca['doneChargingTime'], errors='coerce')

### Feature Engineering: create suitable features for cluster analysis

In [10]:
# Create the charging_duration column
df_ev_ca['charging_duration'] = (df_ev_ca['disconnectTime'] - df_ev_ca['connectionTime']).dt.total_seconds() / 60  # Duration in minutes

# Create the time_of_day column based on connectionTime
def get_time_of_day(time):
    if time.hour < 6:
        return 'Night'
    elif time.hour < 12:
        return 'Morning'
    elif time.hour < 18:
        return 'Afternoon'
    else:
        return 'Evening'

df_ev_ca['time_of_day'] = df_ev_ca['connectionTime'].apply(get_time_of_day)

In [11]:
df_ev_ca['day_of_week'] = df_ev_ca['connectionTime'].dt.day_name()

In [12]:
df_ev_ca['is_weekend'] = df_ev_ca['connectionTime'].dt.weekday >= 5

In [13]:
# Automatically create 4 equal-sized bins for 'kWhDelivered' 
df_ev_ca['kWhDelivered_Category'] = pd.qcut(df_ev_ca['kWhDelivered'], q=4, labels=['Low', 'Medium', 'High', 'Very High'])

In [14]:
df_ev_ca['efficiency_ratio'] = df_ev_ca['kWhDelivered'] / df_ev_ca['charging_duration']

In [15]:
df_ev_ca['charging_duration_category'] = pd.qcut(df_ev_ca['charging_duration'], q=3, labels=['Short', 'Medium', 'Long'])

In [16]:
df_ev_ca

,Unnamed: 0.1,Unnamed: 0,id,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,...,modifiedAt,paymentRequired,requestedDeparture,charging_duration,time_of_day,day_of_week,is_weekend,kWhDelivered_Category,efficiency_ratio,charging_duration_category
0,0,0,5e23b149f9af8b5fe4b973cf,2020-01-02 05:08:54,2020-01-02 11:11:15,2020-01-02 09:31:35,25.016,1_1_179_810_2020-01-02 13:08:53.870034,1,AG-3F30,...,2020-01-02 05:09:39-08:00,True,2020-01-02 12:51:54-08:00,362.350000,Night,Thursday,False,Very High,0.069038,Medium
1,1,1,5e23b149f9af8b5fe4b973d0,2020-01-02 05:36:50,2020-01-02 14:38:21,2020-01-02 12:18:05,33.097,1_1_193_825_2020-01-02 13:36:49.599853,1,AG-1F01,...,2020-01-02 05:37:11-08:00,True,2020-01-02 15:31:50-08:00,541.516667,Night,Thursday,False,Very High,0.061119,Long
2,2,2,5e23b149f9af8b5fe4b973d1,2020-01-02 05:56:35,2020-01-02 16:39:22,2020-01-02 08:35:06,6.521,1_1_193_829_2020-01-02 13:56:35.214993,1,AG-1F03,...,2020-01-02 05:57:17-08:00,True,2020-01-02 06:56:35-08:00,642.783333,Night,Thursday,False,Medium,0.010145,Long
3,3,3,5e23b149f9af8b5fe4b973d2,2020-01-02 05:59:58,2020-01-02 08:38:39,2020-01-02 07:18:45,2.355,1_1_193_820_2020-01-02 13:59:58.309319,1,AG-1F04,...,2020-01-02 06:00:03-08:00,True,2020-01-02 07:04:58-08:00,158.683333,Night,Thursday,False,Low,0.014841,Short
5,5,4,5e23b149f9af8b5fe4b973d3,2020-01-02 06:00:01,2020-01-02 14:08:40,2020-01-02 10:17:30,13.375,1_1_193_819_2020-01-02 14:00:00.779967,1,AG-1F06,...,2020-01-02 06:00:13-08:00,True,2020-01-02 14:24:01-08:00,488.650000,Morning,Thursday,False,High,0.027371,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73563,78871,8670,5d2fbdd3f9af8b4d0dd0d54a,2019-07-01 14:49:12,2019-07-01 18:37:18,2019-07-01 16:14:33,8.399,1_1_179_798_2019-07-01 21:49:11.873404,1,AG-3F18,...,2019-07-01 14:49:37-07:00,True,2019-07-01 15:25:12-07:00,228.100000,Afternoon,Monday,False,Medium,0.036822,Short
73565,78873,8671,5d2fbdd3f9af8b4d0dd0d54b,2019-07-01 14:58:45,2019-07-01 17:39:48,2019-07-01 17:40:21,16.864,1_1_179_794_2019-07-01 21:58:44.571011,1,AG-3F20,...,2019-07-01 14:59:09-07:00,True,2019-07-01 18:52:45-07:00,161.050000,Afternoon,Monday,False,Very High,0.104713,Short
73566,78874,8672,5d2fbdd3f9af8b4d0dd0d54c,2019-07-01 15:02:21,2019-07-01 17:58:50,2019-07-01 17:59:23,18.335,1_1_191_807_2019-07-01 22:02:20.810735,1,AG-4F47,...,2019-07-01 15:02:37-07:00,True,2019-07-01 20:11:21-07:00,176.483333,Afternoon,Monday,False,Very High,0.103891,Short
73568,78876,8673,5d2fbdd3f9af8b4d0dd0d54d,2019-07-01 15:23:44,2019-07-01 19:03:36,2019-07-01 19:04:06,22.815,1_1_179_781_2019-07-01 22:23:32.496137,1,AG-3F31,...,2019-07-01 15:23:43-07:00,True,2019-07-01 17:02:44-07:00,219.866667,Afternoon,Monday,False,Very High,0.103767,Short
73569,78877,8674,5d2fbdd3f9af8b4d0dd0d54e,2019-07-01 15:36:08,2019-07-01 18:10:52,2019-07-01 17:24:32,10.241,1_1_193_819_2019-07-01 22:35:56.104381,1,AG-1F06,...,2019-07-01 15:36:08-07:00,True,2019-07-01 18:47:08-07:00,154.733333,Afternoon,Monday,False,High,0.066185,Short

In [17]:
list(df_ev_ca.columns)

['Unnamed: 0.1',
 'Unnamed: 0',
 'id',
 'connectionTime',
 'disconnectTime',
 'doneChargingTime',
 'kWhDelivered',
 'sessionID',
 'siteID',
 'spaceID',
 'stationID',
 'timezone',
 'userID',
 'WhPerMile',
 'kWhRequested',
 'milesRequested',
 'minutesAvailable',
 'modifiedAt',
 'paymentRequired',
 'requestedDeparture',
 'charging_duration',
 'time_of_day',
 'day_of_week',
 'is_weekend',
 'kWhDelivered_Category',
 'efficiency_ratio',
 'charging_duration_category']

### Filter data to only include relevant cols

In [18]:
df_cluster = df_ev_ca[['charging_duration','time_of_day','day_of_week','is_weekend','kWhDelivered_Category','efficiency_ratio','charging_duration_category']]
df_cluster

,charging_duration,time_of_day,day_of_week,is_weekend,kWhDelivered_Category,efficiency_ratio,charging_duration_category
0,362.350000,Night,Thursday,False,Very High,0.069038,Medium
1,541.516667,Night,Thursday,False,Very High,0.061119,Long
2,642.783333,Night,Thursday,False,Medium,0.010145,Long
3,158.683333,Night,Thursday,False,Low,0.014841,Short
5,488.650000,Morning,Thursday,False,High,0.027371,Medium
...,...,...,...,...,...,...,...
73563,228.100000,Afternoon,Monday,False,Medium,0.036822,Short
73565,161.050000,Afternoon,Monday,False,Very High,0.104713,Short
73566,176.483333,Afternoon,Monday,False,Very High,0.103891,Short
73568,219.866667,Afternoon,Monday,False,Very High,0.103767,Short
73569,154.733333,Afternoon,Monday,False,High,0.066185,Short

### Prepare df for cluster analysis using One-hot encoding and Standardization

In [19]:
# One-hot encoding for categorical features
df_cluster_encoded = pd.get_dummies(df_cluster, columns=['time_of_day', 'day_of_week', 'kWhDelivered_Category', 'charging_duration_category'], drop_first=True)

In [20]:
# Standardize the numerical features
scaler = StandardScaler()
df_cluster_encoded[['charging_duration', 'efficiency_ratio']] = scaler.fit_transform(df_cluster_encoded[['charging_duration', 'efficiency_ratio']])

In [21]:
df_cluster_encoded

,charging_duration,is_weekend,efficiency_ratio,time_of_day_Evening,time_of_day_Morning,time_of_day_Night,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,day_of_week_Wednesday,kWhDelivered_Category_Medium,kWhDelivered_Category_High,kWhDelivered_Category_Very High,charging_duration_category_Medium,charging_duration_category_Long
0,-0.068829,False,0.819622,False,False,True,False,False,False,True,False,False,False,False,True,True,False
1,0.537924,False,0.599746,False,False,True,False,False,False,True,False,False,False,False,True,False,True
2,0.880866,False,-0.815561,False,False,True,False,False,False,True,False,False,True,False,False,False,True
3,-0.758552,False,-0.685177,False,False,True,False,False,False,True,False,False,False,False,False,False,False
5,0.358889,False,-0.337267,False,True,False,False,False,False,True,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73563,-0.523470,False,-0.074879,False,False,False,True,False,False,False,False,False,True,False,False,False,False
73565,-0.750537,False,1.810134,False,False,False,True,False,False,False,False,False,False,False,True,False,False
73566,-0.698271,False,1.787312,False,False,False,True,False,False,False,False,False,False,False,True,False,False
73568,-0.551353,False,1.783886,False,False,False,True,False,False,False,False,False,False,False,True,False,False
73569,-0.771928,False,0.740397,False,False,False,True,False,False,False,False,False,False,True,False,False,False

In [22]:
# Convert all columns to int except 'charging_duration' and 'efficiency_ratio'
cols_to_exclude = ['charging_duration', 'efficiency_ratio']

# Convert all other columns to int
df_cluster_encoded.loc[:, ~df_cluster_encoded.columns.isin(cols_to_exclude)] = \
    df_cluster_encoded.loc[:, ~df_cluster_encoded.columns.isin(cols_to_exclude)].astype(int)

# Confirm the changes
print(df_cluster_encoded.dtypes)

charging_duration                    float64
is_weekend                             int64
efficiency_ratio                     float64
time_of_day_Evening                    int64
time_of_day_Morning                    int64
time_of_day_Night                      int64
day_of_week_Monday                     int64
day_of_week_Saturday                   int64
day_of_week_Sunday                     int64
day_of_week_Thursday                   int64
day_of_week_Tuesday                    int64
day_of_week_Wednesday                  int64
kWhDelivered_Category_Medium           int64
kWhDelivered_Category_High             int64
kWhDelivered_Category_Very High        int64
charging_duration_category_Medium      int64
charging_duration_category_Long        int64
dtype: object

### Optional: use only a few columns, as my kernel keeps crashing using KMeans

In [26]:
#df_cluster_encoded = df_cluster_encoded[['charging_duration','charging_duration_category_Medium','charging_duration_category_Long']]

## Below, multiple approaches for KMeans clustering. all crash my kernel, no matter the df size (e.g reducing dimensionality by removing columns or reducing length by only using a subset of the 60k rows)

### Elbow and Silhouette Score to identify the best number of cluster centers

In [23]:
# Prepare the data for clustering 
X = df_cluster_encoded.values

# Elbow method and Silhouette Score together
inertia = []  # For Elbow
silhouette_scores = []  # For Silhouette Score
range_clusters = range(2, 5)  # Testing cluster sizes from 2 to 10

for k in range_clusters:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)  # Sum of squared distances to nearest cluster center
    silhouette_scores.append(silhouette_score(X, kmeans.labels_))

# Plotting the results
fig, ax1 = plt.subplots(figsize=(12, 6))

# Elbow method plot
ax1.plot(range_clusters, inertia, marker='o')
ax1.set_xlabel('Number of Clusters')
ax1.set_ylabel('Inertia')
ax1.set_title('Elbow Method (Inertia)')

# Silhouette score plot
ax2 = ax1.twinx()
ax2.plot(range_clusters, silhouette_scores, marker='o', color='red')
ax2.set_ylabel('Silhouette Score')

plt.show()

:

### MiniBatchKMeans should be a more efficient alternative to KMeans, still crashes my kernel. also, X_sample only uses 5k out of the 60k

In [28]:
from sklearn.cluster import MiniBatchKMeans
import matplotlib.pyplot as plt

# Optional: Use a smaller sample for testing
df_sample = df_cluster_encoded.sample(n=5000, random_state=42)
X_sample = df_sample.values
X_sample

# Elbow method using MiniBatchKMeans
inertia = []
range_clusters = range(2, 6)

for k in range_clusters:
    kmeans = MiniBatchKMeans(n_clusters=k, random_state=42, batch_size=1000)
    kmeans.fit(X_sample)
    inertia.append(kmeans.inertia_)

# Plot the Elbow Method
plt.figure(figsize=(12, 6))
plt.plot(range_clusters, inertia, marker='o')
plt.xlabel('Number of Clusters')
plt.ylabel('Inertia')
plt.title('Elbow Method using MiniBatchKMeans (Optimized)')
plt.show()

:

In [ ]:
### This is just the first approach but without the Silhouette Score, still crashes

In [26]:
# Prepare the data for clustering (assuming df_cluster_encoded is already scaled and encoded)
X = df_cluster_encoded.values

# Elbow method calculation
inertia = []  # For Elbow Method
range_clusters = range(2, 6)  # Testing cluster sizes from 2 to 10

for k in range_clusters:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)  # Sum of squared distances to nearest cluster center

# Plotting the Elbow Method results
plt.figure(figsize=(12, 6))
plt.plot(range_clusters, inertia, marker='o')
plt.xlabel('Number of Clusters')
plt.ylabel('Inertia')
plt.title('Elbow Method for Optimal Cluster Selection')
plt.show()

:

In [ ]:
# TODO
# KMeans crashes my kernel no matter the df size ???
# try other clustering algorithms (Hierarchical, DBSCAN)
# interpret and label the resulting clusters
# answer task question: What is the value of identifying different types of charging sessions?